### ISSUE TITLE
miekg no method exists

### ISSUE THREAD

**Issue by chencxin** [DNS-OARC/golang-dns-server-doq#2]
dns.TsigGenerateProvider  dns.TsigVerifyProvider  Both methods are private in miekg，

I manually changed it to a common method, but failed to run the test case

<img width="891" alt="image" src="https://user-images.githubusercontent.com/40486630/173730623-f4d3cfd4-d73d-44db-a4c9-b53513cb45f5.png">

**Comment by jelu** [comment]
Waiting on this https://github.com/miekg/dns/pull/1379

**Comment by jelu** [comment]
@van-scott Try again now :)
