### ISSUE TITLE
Licensing as MPL? 

### ISSUE THREAD

**Issue by miekg** [DNS-OARC/golang-dns-server-doq#4]
Question: this code is licensed under MPL? I don't think that's allowed, as chunks have been copied from miekg/dns

(I honestly don't know how intertwined or different MPL and MIT are)

**Comment by jelu** [comment]
Yes, MPL-2.0 but I don't really consider any code copied in that sense. It's based on it because I wanted to mimic it so it's easy for people to use if they used `dns.Server`.

What code do you considered that this module copies?

**Comment by miekg** [comment]
e.g: https://github.com/miekg/dns/blob/master/server.go#L610
and https://github.com/DNS-OARC/golang-dns-server-doq/blob/main/server.go#L253

I honestly don't think you can just re-license like this.
